import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          id="show-banner"
          dangerouslySetInnerHTML={{
            __html: `
            const html = document.documentElement;
            const canvas = document.getElementById("hero-lightpass");
            const context = canvas.getContext("2d");

            const frameCount = 148;
            const currentFrame = index => (
            \`https://www.apple.com/105/media/us/airpods-pro/2019/1299e2f5_9206_4470_b28e_08307a42f19b/anim/sequence/large/01-hero-lightpass/\${index.toString().padStart(4, '0')}.jpg\`
            )

            const preloadImages = () => {
            for (let i = 1; i < frameCount; i++) {
              const img = new Image();
              img.src = currentFrame(i);
            }
            };

            const img = new Image()
            img.src = currentFrame(1);
            canvas.width=1158;
            canvas.height=770;
            img.onload=function(){
            context.drawImage(img, 0, 0);
            }

            const updateImage = index => {
            img.src = currentFrame(index);
            context.drawImage(img, 0, 0);
            }

            window.addEventListener('scroll', () => {
            const scrollTop = html.scrollTop;
            const maxScrollTop = html.scrollHeight - window.innerHeight;
            const scrollFraction = scrollTop / maxScrollTop;
            const frameIndex = Math.min(
              frameCount - 1,
              Math.ceil(scrollFraction * frameCount)
            );

            requestAnimationFrame(() => updateImage(frameIndex + 1))
            });

            preloadImages()
              `,
          }}
        />
      </Head>

      <nav class="navbar">
      <div class="logo">ÆLijah</div>
      <ul class="nav-links">
        <div class="menu">
          <li><a href="/">Home</a></li>
          <li><a href="/">About</a></li>
          <li class="services">
            <a href="/">Services</a>
            <ul class="dropdown">
              <li><a href="/">Dropdown 1 </a></li>
              <li><a href="/">Dropdown 2</a></li>
              <li><a href="/">Dropdown 2</a></li>
              <li><a href="/">Dropdown 3</a></li>
              <li><a href="/">Dropdown 4</a></li>
            </ul>
          </li>
          <li><a href="/">Pricing</a></li>
          <li><a href="/">Contact</a></li>
        </div>
      </ul>
    </nav>

      <main className={styles.main}>
        <canvas id="hero-lightpass" />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
